### ISSUE TITLE
model release

### ISSUE THREAD

**Issue by ZcsrenlongZ** [jiaqixuac/MAP-Net#1]
Hi! Thanks for your job! Will you release the trained model?

**Comment by koihoo** [comment]
> 

also question

**Comment by CodeStarting-design** [comment]
Hi! Thanks for your job! Will you release the trained model?

**Comment by DanielG1010** [comment]
Hi! Thanks for your job! Will you release the trained model?

**Comment by jiaqixuac** [comment]
Readme updated. You can find one model checkpoint trained on HazeWorld [here](https://drive.google.com/file/d/1sinGqjsL5eWlTOqYoa5Q3QW-NYEboh73/view?usp=share_link).
