### ISSUE TITLE
Too much time for test

### ISSUE THREAD

**Issue by HaoyouDeng** [jiaqixuac/MAP-Net#11]
Hi, when I test the trained ckp on the test dataset of HazeWorld, it takes too much time, about 20s/task using V100.
Is this a normal time cost? Thanks!

**Comment by jiaqixuac** [comment]
It takes 10+ hours in my case.

**Comment by HaoyouDeng** [comment]
Is this a issue of mmcv or mmedit? I find that gpu-util is under 10% at most of the time.

**Comment by YuZheng9** [comment]
> Is this a issue of mmcv or mmedit? I find that gpu-util is under 10% at most of the time.

Hi, I had the same problem and wanted to ask if you solved it yet

**Comment by HaoyouDeng** [comment]
> > Is this a issue of mmcv or mmedit? I find that gpu-util is under 10% at most of the time.
> 
> Hi, I had the same problem and wanted to ask if you solved it yet

@YuZheng9 I made two changes, and it can be faster.

1. Do not save images to disks during evaluation.
2. Use gpus to calculate psnr or ssim. I use the package Kornia, and the result is similar to the code in this repository.

Hope this is helpful to you.

**Comment by YuZheng9** [comment]
> > > Is this a issue of mmcv or mmedit? I find that gpu-util is under 10% at most of the time.
> > 
> > 
> > Hi, I had the same problem and wanted to ask if you solved it yet
> 
> @YuZheng9 I made two changes, and it can be faster.
> 
> 1. Do not save images to disks during evaluation.
> 2. Use gpus to calculate psnr or ssim. I use the package Kornia, and the result is similar to the code in this repository.
> 
> Hope this is helpful to you.

Thank you very much for your reply and good luck with your studies and papers!

**Comment by HaoyouDeng** [comment]
@YuZheng9 Hi, sorry to bother you. Have you tried to reproduce the results on REVIDE? I have some problems with it. May I have a private discussion with you? My email: haoyoudeng@hust.edu.cn.

**Comment by hhhshv** [comment]
> > > 这是 mmcv 还是 mmedit 的问题？我发现 gpu-util 在大多数时候都低于 10%。
> > 
> > 
> > 嗨，我遇到了同样的问题，想问问你是否解决了
> 
> 我做了两个更改，它可以更快。
> 
> 1. 在评估期间，请勿将映像保存到磁盘。
> 2. 使用 gpu 计算 psnr 或 ssim。我使用包 Kornia，结果与此存储库中的代码类似。
> 
> 希望这对你有所帮助。

请问，这个模型能不能用自己的数据集进行训练和测试？
