### ISSUE TITLE
Computing Resources

### ISSUE THREAD

**Issue by Zhang-Jing-Xuan** [jiaqixuac/MAP-Net#2]
Hi. How many GPUs did you use to train on the HazeWorld dataset and how long did it take to train?

**Comment by jiaqixuac** [comment]
It should take less than one day with 4 2080 in the current setting.

**Comment by ZcsrenlongZ** [comment]
Hi! How to train in REVIDE dataset?

**Comment by jiaqixuac** [comment]
On REVIDE, we use heavier data augmentation, e.g., resizing with random scales, since REVIDE only contains 42 training videos, following CG-IDN. The patch size of input video frames is 384×384.

**Comment by ZcsrenlongZ** [comment]
> On REVIDE, we use heavier data augmentation, e.g., resizing with random scales, since REVIDE only contains 42 training videos, following CG-IDN. The patch size of input video frames is 384×384.

Thanks for your relpy! Where could I get the trained model on REVIDE dataset?

**Comment by Zhang-Jing-Xuan** [comment]
> It should take less than one day with 4 2080 in the current setting.

Thanks for your relpy!

**Comment by Zhang-Jing-Xuan** [comment]
> > On REVIDE, we use heavier data augmentation, e.g., resizing with random scales, since REVIDE only contains 42 training videos, following CG-IDN. The patch size of input video frames is 384×384.
> 
> Thanks for your relpy! Where could I get the trained model on REVIDE dataset?

I finished training but I got a problem when I tried to run the evaluation code.

**Comment by fanjunkai1** [comment]
> > I have a question I'd like to ask, what is the structure of the meta_info_GT.txt file on REVIDE ?
> 
> meta_info_GT.txt file should contain the video sequence names and number of frames.
> 
> ```
> C002_1 21
> ...
> ```

Thanks for your reply!

**Comment by fanjunkai1** [comment]
> > > On REVIDE, we use heavier data augmentation, e.g., resizing with random scales, since REVIDE only contains 42 training videos, following CG-IDN. The patch size of input video frames is 384×384.
> > 
> > 
> > Thanks for your relpy! Where could I get the trained model on REVIDE dataset?
> 
> I finished training but I got a problem when I tried to run the evaluation code.

I have a question I'd like to ask, what is the structure of the meta_info_GT.txt file on REVIDE ?

**Comment by jiaqixuac** [comment]
> 
> I have a question I'd like to ask, what is the structure of the meta_info_GT.txt file on REVIDE ?

meta_info_GT.txt file should contain the video sequence names and number of frames.
```
C002_1 21
...
```

**Comment by shinenhy** [comment]
> 在当前设置中，4 2080 应该需要不到一天的时间。

Can I train with a 3060?

**Comment by jiaqixuac** [comment]
> > 在当前设置中，4 2080 应该需要不到一天的时间。
> 
> Can I train with a 3060?

Sorry, I haven't tried with 3060.

**Comment by shinenhy** [comment]
> > > 在当前设置中，4 2080 应该需要不到一天的时间。
> > 
> > 
> > Can I train with a 3060?
> 
> Sorry, I haven't tried with 3060.

oh,  I want to know whether one GPU can train the network and loading ConvNeXt's parameters misses some parameters, such as norm0.weight etc. I don't know why.
