### ISSUE TITLE
Evaluation procedure ended abruptly.

### ISSUE THREAD

**Issue by Zhang-Jing-Xuan** [jiaqixuac/MAP-Net#3]
Hi. I have finished training on the REVIDE dataset and I tried to evaluate the iter_40000.pth checkpoint. However, after the warning:"[Shape mismatch] lq: torch.Size([1, 54, 3, 900, 1354]), gt: torch.Size([1, 54, 3, 1800, 2708])", the evaluation procedure ended abruptly. How to solve this problem? Thank you.

**Comment by jiaqixuac** [comment]
Make sure you have enough GPU memory to run the inference.

**Comment by Zhang-Jing-Xuan** [comment]
Thanks for your reply.
